# Generated by Django 5.1.4 on 2024-12-17 19:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('was_published_recently', django.db.models.manager.Manager()),
            ],
        ),
    ]
